services:
  postgres_primary:
    extends:
      file: docker-compose.base.yml
      service: postgres_primary
    volumes:
      - zbugs_pgdata_upstream:/var/lib/postgresql/data
      - ./share_sql/base.sql:/docker-entrypoint-initdb.d/a.sql
      - ./1gb_upstream/init.sql:/docker-entrypoint-initdb.d/b.sql
      - ./share_sql/index.sql:/docker-entrypoint-initdb.d/c.sql
      - ./data/1gb:/data
  postgres_replica:
    extends:
      file: docker-compose.base.yml
      service: postgres_replica
volumes:
  zbugs_pgdata_sync:
    driver: local
  zbugs_pgdata_upstream:
    driver: local
